set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Cross-platform automatic search hints for ARM GNU Toolchain
set(ARM_TOOLCHAIN_HINTS "")
if(WIN32)
    if(DEFINED ENV{ARM_TOOLCHAIN_PATH})
        list(APPEND ARM_TOOLCHAIN_HINTS "$ENV{ARM_TOOLCHAIN_PATH}")
    endif()
    file(GLOB WIN_ST_HINTS "$ENV{LOCALAPPDATA}/stm32cube/bundles/gnu-tools-for-stm32/*/bin")
    file(GLOB WIN_CLT_HINTS "$ENV{SystemDrive}/ST/STM32CubeCLT*/GNU-tools-for-STM32/bin")
    file(GLOB WIN_ARM_HINTS "$ENV{ProgramFiles}/Arm GNU Toolchain*/bin")
    list(APPEND ARM_TOOLCHAIN_HINTS ${WIN_ST_HINTS} ${WIN_CLT_HINTS} ${WIN_ARM_HINTS})
elseif(APPLE)
    list(APPEND ARM_TOOLCHAIN_HINTS "/opt/homebrew/bin" "/usr/local/bin")
elseif(UNIX)
    file(GLOB LINUX_CLT_HINTS "/opt/st/stm32cubeclt*/GNU-tools-for-STM32/bin")
    list(APPEND ARM_TOOLCHAIN_HINTS "/usr/bin" "/usr/local/bin" ${LINUX_CLT_HINTS})
endif()

find_program(ARM_GCC_PATH arm-none-eabi-gcc HINTS ${ARM_TOOLCHAIN_HINTS})
find_program(ARM_GXX_PATH arm-none-eabi-g++ HINTS ${ARM_TOOLCHAIN_HINTS})
find_program(ARM_OBJCOPY_PATH arm-none-eabi-objcopy HINTS ${ARM_TOOLCHAIN_HINTS})
find_program(ARM_OBJDUMP_PATH arm-none-eabi-objdump HINTS ${ARM_TOOLCHAIN_HINTS})
find_program(ARM_SIZE_PATH arm-none-eabi-size HINTS ${ARM_TOOLCHAIN_HINTS})

if(ARM_GCC_PATH)
    set(CMAKE_C_COMPILER "${ARM_GCC_PATH}")
    set(CMAKE_ASM_COMPILER "${ARM_GCC_PATH}")
else()
    set(CMAKE_C_COMPILER arm-none-eabi-gcc)
    set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
endif()

if(ARM_GXX_PATH)
    set(CMAKE_CXX_COMPILER "${ARM_GXX_PATH}")
else()
    set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
endif()

if(ARM_OBJCOPY_PATH)
    set(CMAKE_OBJCOPY "${ARM_OBJCOPY_PATH}" CACHE FILEPATH "Path to objcopy" FORCE)
else()
    set(CMAKE_OBJCOPY arm-none-eabi-objcopy CACHE FILEPATH "Path to objcopy" FORCE)
endif()

if(ARM_OBJDUMP_PATH)
    set(CMAKE_OBJDUMP "${ARM_OBJDUMP_PATH}" CACHE FILEPATH "Path to objdump" FORCE)
else()
    set(CMAKE_OBJDUMP arm-none-eabi-objdump CACHE FILEPATH "Path to objdump" FORCE)
endif()

if(ARM_SIZE_PATH)
    set(CMAKE_SIZE "${ARM_SIZE_PATH}" CACHE FILEPATH "Path to size tool" FORCE)
else()
    set(CMAKE_SIZE arm-none-eabi-size CACHE FILEPATH "Path to size tool" FORCE)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Target specs & flags with Debug Symbols (-O0 -g3)
if(PLATFORM MATCHES "stm32h7")
    set(CPU_FLAGS "-mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb")
else()
    set(CPU_FLAGS "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb")
endif()

set(CMAKE_C_FLAGS "${CPU_FLAGS} -O0 -g3 -fdata-sections -ffunction-sections -Wall -Wextra" CACHE STRING "C Flags")
set(CMAKE_CXX_FLAGS "${CPU_FLAGS} -O0 -g3 -fdata-sections -ffunction-sections -Wall -Wextra" CACHE STRING "CXX Flags")
set(CMAKE_EXE_LINKER_FLAGS "${CPU_FLAGS} --specs=nano.specs -Wl,--gc-sections" CACHE STRING "Linker Flags")
