# STM32F4 Platform Build Specification

set(PLATFORM_DEFINES
    USE_HAL_DRIVER
    STM32F407xx
)

set(PLATFORM_INCLUDES
    ${CMAKE_CURRENT_LIST_DIR}/board
    ${CMAKE_CURRENT_LIST_DIR}/board/config
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Core/Inc
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Include
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/CMSIS/Include
)

# Automatically scan all Core sources, HAL Drivers, and Driver Adapters
file(GLOB PLATFORM_CORE_SOURCES "${CMAKE_CURRENT_LIST_DIR}/cubemx/Core/Src/*.c")
file(GLOB PLATFORM_HAL_SOURCES "${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/STM32F4xx_HAL_Driver/Src/*.c")
file(GLOB PLATFORM_ADAPTER_SOURCES "${CMAKE_CURRENT_LIST_DIR}/board/adapters/*.c")

# Suppress compiler warnings for third-party HAL drivers generated by CubeMX
set_source_files_properties(${PLATFORM_HAL_SOURCES} PROPERTIES COMPILE_FLAGS "-w")

set(PLATFORM_SOURCES
    # Core & Startup
    ${PLATFORM_CORE_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/startup_stm32f407xx.s

    # Auto-scanned HAL Drivers (CubeMX exports only enabled peripheral drivers here)
    ${PLATFORM_HAL_SOURCES}

    # Driver Adapters
    ${PLATFORM_ADAPTER_SOURCES}
)

set(PLATFORM_LINK_OPTIONS
    -T${CMAKE_CURRENT_LIST_DIR}/cubemx/STM32F407xx_FLASH.ld
)
