# STM32H7A3ZIQ Platform Build Specification

set(PLATFORM_DEFINES
    USE_PWR_DIRECT_SMPS_SUPPLY
    USE_HAL_DRIVER
    STM32H7A3xxQ
    USE_FREERTOS
)

set(PLATFORM_INCLUDES
    ${CMAKE_CURRENT_LIST_DIR}/../common/inc
    ${CMAKE_CURRENT_LIST_DIR}/board
    ${CMAKE_CURRENT_LIST_DIR}/drivers
    ${CMAKE_CURRENT_LIST_DIR}/mcal
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Core/Inc
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/STM32H7xx_HAL_Driver/Inc
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/CMSIS/Device/ST/STM32H7xx/Include
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/include
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/CMSIS/RTOS2/Include
)

# Automatically scan all Core sources, HAL Drivers, Drivers, and MCAL
file(GLOB PLATFORM_CORE_SOURCES "${CMAKE_CURRENT_LIST_DIR}/cubemx/Core/Src/*.c")
file(GLOB PLATFORM_HAL_SOURCES "${CMAKE_CURRENT_LIST_DIR}/cubemx/Drivers/STM32H7xx_HAL_Driver/Src/*.c")
file(GLOB PLATFORM_DRIVER_SOURCES "${CMAKE_CURRENT_LIST_DIR}/drivers/*.c")
file(GLOB PLATFORM_MCAL_SOURCES "${CMAKE_CURRENT_LIST_DIR}/mcal/*.c")

# FreeRTOS sources from CubeMX
set(PLATFORM_FREERTOS_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/croutine.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/list.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/queue.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/tasks.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/timers.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
)

# Suppress compiler warnings for third-party HAL drivers & FreeRTOS generated by CubeMX
set_source_files_properties(${PLATFORM_HAL_SOURCES} ${PLATFORM_FREERTOS_SOURCES} PROPERTIES COMPILE_FLAGS "-w")

set(PLATFORM_SOURCES
    # Core & Startup
    ${PLATFORM_CORE_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/cubemx/startup_stm32h7a3xxq.s

    # Auto-scanned HAL Drivers
    ${PLATFORM_HAL_SOURCES}

    # FreeRTOS Kernel Sources
    ${PLATFORM_FREERTOS_SOURCES}

    # Board IoHwAb, Device Drivers & MCAL
    ${CMAKE_CURRENT_LIST_DIR}/board/board.c
    ${PLATFORM_DRIVER_SOURCES}
    ${PLATFORM_MCAL_SOURCES}
)

set(PLATFORM_LINK_OPTIONS
    -T${CMAKE_CURRENT_LIST_DIR}/cubemx/STM32H7A3xx_FLASH.ld
    -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/${APP_NAME}.map
)
